export const deviceValues = [
  {
    valueRange: '0 - 40,000',
    id: 1,
    price: 3000,
  },
  {
    valueRange: '40,001 - 100,000',
    id: 2,
    price: 7000,
  },
  {
    valueRange: '100,001 - 350,000',
    id: 3,
    price: 23000,
  },
  {
    valueRange: '350,001 - 600,000',
    id: 4,
    price: 40000,
  },
  {
    valueRange: '600,000 - Above',
    id: 4,
    price: 120000,
  },
];

export const deviceTypes = [
  {
    name: 'Laptop(PC)',
    brands: [
      'Apple',
      'Dell',
      'Lenovo',
      'Asus',
      'HP',
      'Acer',
      'MSI',
      'Microsoft',
      'Toshiba',
      'Samsung',
    ],
  },
  {
    name: 'Smartphone',
    brands: [
      'Samsung',
      'Huawei',
      'Apple',
      'Techno',
      'Itel',
      'Infinix',
      'Apple',
      'Xiaomi',
      'Oppo',
      'Vivo',
      'Motorola',
      'Lenovo',
      'LG',
      'Nokia',
      'Google Pixel',
      'Gionee',
    ],
  },
  {
    name: 'Desktop Computer',
    brands: [
      'Intel',
      'Asus',
      'HP',
      'Alienware',
      'Acer',
      'Toshiba',
      'Apple',
      'Sony Computer',
      'Compaq',
      'Gateway',
      'Velocity Micro',
      'eMachines',
      'CyberPower',
      'AOpen',
      'Microsoft',
      'BMI',
      'Zotac',
      'ECS(LIVA)',
    ],
  },
];
